# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opus_login', '0003_employerform_studentform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
