# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus_login', '0004_auto_20160206_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerform',
            name='tester',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='test',
        ),
        migrations.AddField(
            model_name='employerform',
            name='contact_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerform',
            name='referral',
            field=models.CharField(choices=[('1', 'Friends & Family'), ('2', 'Other Websites'), ('3', 'Advertisements'), ('4', 'High School or University'), ('5', 'Other')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentform',
            name='birth_date',
            field=models.DateField(default='1990-12-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentform',
            name='contact_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentform',
            name='referral',
            field=models.CharField(choices=[('1', 'Friends & Family'), ('2', 'Other Websites'), ('3', 'Advertisements'), ('4', 'High School or University'), ('5', 'Other')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
